name: halendar_front
description: "Halendar front-end"
publish_to: 'none'
version: 2.1.2

environment:
  sdk: ^3.13.3

dependencies:
  file_picker: ^11.0.2
  file_saver: ^0.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_tts: ^4.2.5
  google_fonts: ^8.2.0
  hive_flutter: ^1.1.0
  http: ^1.6.0
  intl: ^0.20.2
  lasuite_ui:
    path: packages/lasuite_ui
  mobile_scanner: ^7.2.1
  path_provider: ^2.1.6
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.3
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  flutter_local_notifications: ^22.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
